// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'menu__item': string;
  'menu__sublist': string;
  'menu__sublist__item': string;
  'menu__sublist__item__links': string;
}
export const cssExports: CssExports;
export default cssExports;
