// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'catalog': string;
  'catalog__list': string;
  'catalog__list__item': string;
  'catalog__list__item__img': string;
  'catalog__list__item__price': string;
  'catalog__list__item__sale': string;
  'catalog__list__item__title': string;
  'catalog__nav': string;
  'catalog__nav__filter': string;
  'catalog__nav__location': string;
  'catalog__nav__title': string;
}
export const cssExports: CssExports;
export default cssExports;
