// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'item__box': string;
  'item__box__img': string;
  'item__box__price': string;
  'item__box__sale': string;
  'item__box__title': string;
  'item__nav': string;
}
export const cssExports: CssExports;
export default cssExports;
