// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header__logo': string;
  'header__nav': string;
  'header__nav__item': string;
  'header__search': string;
  'header__search__btn': string;
  'header__search__input': string;
  'layout': string;
}
export const cssExports: CssExports;
export default cssExports;
