// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fade': string;
  'slider': string;
  'slider__box': string;
  'slider__item': string;
  'slider__item__text': string;
  'slider__nav': string;
  'slider__nav__item': string;
  'slider__nav__item__active': string;
}
export const cssExports: CssExports;
export default cssExports;
